# Generated by Django 5.0.3 on 2024-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='reservation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
